### ISSUE TITLE
Plex API Only via docker?

### ISSUE THREAD

**Issue by LSL1337** [NitriKx/docker-Plex-Cleaner#1]
I Just started using Plex Cleaner (thanks to your docker). I think I'm starting to get a hang of it, but starting it with docker i think makes it a bit more difficult for a beginner.

my question is. Can this work in docker without plex_delete true?
Under my limited test time I got the following:
Plex_delete true can delete watched movies via web (Plex API), But if I set it to false, It can't. which is kinda makes sense.  (I want to try the copy and move commands as well, and plex API probably doesn't support these)

They are in a seperate docker, this one doesn't have 'OS' access to the filesystem of the plex/media one.
can this be fixed? maybe i mount the same volume on this docker as well. could it work?

thank you!
btw I'm running unraid, not sure if it helps.

**Comment by LSL1337** [comment]
seems like it worked, I don't know why I haven't though of it before posting.
this works great, thanks again for the docker!

**Comment by NitriKx** [comment]
Yep mounting the plex volume is the right solution. I can materialize this by adding a new VOLUME (pointing to /data).

I also going to add these use case in the README. 

Thanks for testing this!
