### ISSUE TITLE
Use crontab instead of infinite loop 

### ISSUE THREAD

**Issue by NitriKx** [NitriKx/docker-Plex-Cleaner#2]
The bash loop prevents the container to stop when we press Ctrl+C

**Comment by LSL1337** [comment]
is this customizable?
I don't want to check every five minutes a 500+ movie library.
once or twice a day is enough for me.
is there a way i can change the crontab values?
thanks!

**Comment by NitriKx** [comment]
Yep now you can define an environnement variable:
```
docker run ... -e "EXECUTION_CRON_EXPRESSION=*/5 * * * *" nitrikx/plex-cleaner
```

**Comment by LSL1337** [comment]
cool
THANKS!

**Comment by NitriKx** [comment]
I should add this in the README.
You're welcome!
