### ISSUE TITLE
Pass arguments

### ISSUE THREAD

**Issue by ngovil21** [NitriKx/docker-Plex-Cleaner#3]
https://github.com/NitriKx/docker-Plex-Cleaner/blob/0169ed58688a977cf97e4a087f672b7996ab6a5a/run-plexcleaner.sh#L5

Don't you need to pass the arguments to the plexcleaner script as well with `"$@"`

**Comment by NitriKx** [comment]
Doh I've done a big refactoring and I forgotten to forward the parameters inside the script. I'm going to fix it.

**Comment by NitriKx** [comment]
I've pushed to correction with a little bonus : I've added a test to validate that the parameters are passed (both in insole execution and CRON mode)
